project_name: genval

# setups builds for linux, windows and darwin on amd64 and arm64
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

  flags:
    # trims path
    - -trimpath
  ldflags:
    - -s -w
    - -X main.Version={{ .Tag }}
    - -X .Runtime.Goarch={{ .Arch }}
    - -X .Runtime.Gooss={{ .Os }}
    - -X main.Date={{ .CommitDate }}
    - -X main.Commit={{ .FullCommit }}
    - -X main.GitTreeState={{ .GitTreeState }}


checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

# Adds Changelog to the release
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Upgrade:"
      - "^WIP:"
      - '^.*?Bump(\([[:word:]]+\))?.+$'
      - '^.*?[Bot](\([[:word:]]+\))?.+$'

# signs the artifacts
signs:
- cmd: cosign
  certificate: '${artifact}.crt'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
    - "--yes"
  # artifacts: checksum
  artifacts: all
  output: true

