project_name: genval

# setups builds for linux, windows and darwin on amd64 and arm64
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

  flags:
    # trims path
    - -trimpath
  ldflags:
  - -X sigs.k8s.io/release-utils/version.gitVersion={{ .Tag }}
  - -X sigs.k8s.io/release-utils/version.gitCommit={{ .FullCommit }}
  - -X sigs.k8s.io/release-utils/version.gitTreeState={{ .GitTreeState }}
  - -X sigs.k8s.io/release-utils/version.buildDate={{ .Date }}


checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

# Adds Changelog to the release
changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Updates'
      regexp: '^.*?update(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: ^(?i).*?fix\w*(\([[:word:]]+\))??!?:.+$
      order: 200
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Upgrade:"
      - "^WIP:"
      - '^.*?Bump(\([[:word:]]+\))?.+$'
      - '^.*?[Bot](\([[:word:]]+\))?.+$'

# signs the artifacts
signs:
- cmd: cosign
  certificate: '${artifact}.crt'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
    - "--yes"
  # artifacts: checksum
  artifacts: all
  output: true

