apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
    name: xjetpostgresqls.database.wk
spec:
    claimNames:
        kind: JetPostgreSQL
        plural: jetpostgresqls
    group: database.wk
    names:
        kind: XJetPostgreSQL
        plural: xjetpostgresqls
    versions:
        - name: v1alpha1
          referenceable: true
          schema:
            openAPIV3Schema:
                properties:
                    spec:
                        properties:
                            parameters:
                                properties:
                                    dbName:
                                        description: name of the new DB inside the DB instance - string
                                        type: string
                                    instanceSize:
                                        description: instance size - string
                                        enum:
                                            - small
                                            - medium
                                            - large
                                        type: string
                                    storageGB:
                                        description: size of the Database in GB - integer
                                        type: integer
                                required:
                                    - storageGB
                                    - dbName
                                    - instanceSize
                                type: object
                        required:
                            - parameters
                        type: object
                type: object
          served: true
