apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        version: main
    name: nginx-deployment
spec:
    replicas: 3
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                version: cuetest
        spec:
            containers:
                - image: nginx:1.14.2
                  name: nginx
                  ports:
                    - containerPort: 80
                  securityContext:
                    privileged: false
                    runAsNonRoot: true
            securityContext:
                fsGroup: 2000
                runAsUser: 1000
