apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        version: changeMe
    name: nginx-deployment
spec:
    replicas: 3
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                version: changeMe
        spec:
            containers:
                - image: nginx:1.14.2
                  name: nginx
                  ports:
                    - containerPort: 80
                  resources:
                    limits:
                        cpu: 100m
                        memory: 256Mi
                    requests:
                        cpu: 100m
                        memory: 256Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    privileged: false
                    runAsGroup: 1001
                    runAsNonRoot: true
                    runAsUser: 1001
            securityContext:
                fsGroup: 2000
                runAsUser: 1000
