apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cueTest
        version: main
    namespace: websites
spec:
    minReadySeconds: 5
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: cueTest
    template:
        metadata:
            labels:
                app: cueTest
                version: cuetest
        spec:
            containers:
                - image: nginx:1.20
                  imagePullPolicy: Always
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        port: 80
                    initialDelaySeconds: 6
                    periodSeconds: 10
                  name: website
                  ports:
                    - containerPort: 80
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        port: 80
                    initialDelaySeconds: 6
                    periodSeconds: 10
                  securityContext:
                    privileged: false
                    runAsNonRoot: true
