# STAGE 0
  FROM cgr.dev/chainguard/python:latest-dev As builder
  ENV APP_HOME=/app
  RUN useradd -m -s /bin/bash -d $APP_HOME myappuser
  WORKDIR $APP_HOME
  COPY requirements.txt $APP_HOME/
  RUN pip install --no-cache-dir -r requirements.txt
  COPY src/ $APP_HOME/src/

# STAGE 1
  FROM cgr.dev/chainguard/static:latest
  ENV APP_USER=myappuser
  ENV APP_HOME=/app
  RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
  WORKDIR $APP_HOME
  COPY --from=builder $APP_HOME /usr/local/lib/python3.9/site-packages/
  COPY src/ $APP_HOME/src/
  USER $APP_USER
  CMD ["python", "src/app.py"]
