package cmd

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/intelops/genval/llm"
)

var genaiCmd = &cobra.Command{
	Use:   "genai",
	Short: "Generates secure configuration files leveraging AI",
	Long: `Interacts with LLM backends ( currently supported: OpenAI and llama3) using configuration provided by the user through CLI args or a config file in YAML format. A user need to set an assistant to work with, currently supported assistants are Cue, CEL, Rego, Dockerfile, Regex. genai based on the assistant and the user prompt will generate desired a secure IaC configuration by interacting with the chosen LLM. If interacting with OpenAI's 4omodels, a user would need to provide aan API key as an ENV Variable (OPENAI_KEY) for authenticating wtth the LLM backend.

	To enhance the reponse generated by the LLM, it is advisable to run 'genval genai init' before using genai command.
// Examples:
	genval genai --assistant dockerfile --model GPT4 --prompt "Create a Dockefile for a sample python project"

	`,
	RunE: runGenaiCmd,
}

type genaiFlags struct {
	model            string
	endpoint         string
	prompt           string
	assistant        string
	userSystemPrompt string
	backend          string
}

var (
	genaiArgs  genaiFlags
	configFile string
)

func init() {
	// Define Cobra flags
	genaiCmd.Flags().StringVarP(&genaiArgs.model, "model", "m", "", "Select the AI model (e.g., GPT4 or Ollama)")
	genaiCmd.Flags().StringVarP(&genaiArgs.endpoint, "endpoint", "e", "", "Specify the endpoint for the LLM")
	genaiCmd.Flags().StringVarP(&genaiArgs.prompt, "prompt", "p", "", "Provide the user prompt for LLM")
	genaiCmd.Flags().StringVarP(&genaiArgs.assistant, "assistant", "a", "", "Specify the assistant for generating IaC files")
	genaiCmd.Flags().StringVarP(&genaiArgs.userSystemPrompt, "user-system-prompt", "u", "", "Provide the system prompt. Only if assistant is set to user")
	genaiCmd.Flags().StringVarP(&configFile, "config", "c", "", "Path to config file (YAML format)")

	// Add the genai command to root
	rootCmd.AddCommand(genaiCmd)
}

// runGenaiCmd is the main execution function for the genai command
func runGenaiCmd(cmd *cobra.Command, args []string) error {
	// Load configuration
	cfg, err := loadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Conditionally call the appropriate LLM backend based on the model
	ctx := context.Background()
	if cfg.Model == "GPT4" {
		resp, err := cfg.GenerateOpenAIResponse(ctx, cfg.Backend, cfg.UserSystemPrompt, cfg.UserPrompt)
		if err != nil {
			return fmt.Errorf("failed to generate OpenAI response: %w", err)
		}
		fmt.Println("OpenAI Response:", resp)
	} else if cfg.Model == "ollama" {
		resp, err := cfg.GenerateOllamaResponse(ctx, cfg.Model, cfg.UserSystemPrompt, cfg.UserPrompt)
		if err != nil {
			return fmt.Errorf("failed to generate Ollama response: %w", err)
		}
		fmt.Println("Ollama Response:", resp)
	} else {
		return fmt.Errorf("unsupported model: %s", cfg.Model)
	}

	return nil
}

// loadConfig loads the configuration from either flags or config file.
func loadConfig() (*llm.LLMConfig, error) {
	// If config file is provided, load from it
	if configFile != "" {
		config, err := llm.LoadConfig(configFile)
		if err != nil {
			return nil, err
		}
		mergeFlagsWithConfig(config)
		return config, nil
	}

	// If no config file is provided, load from flags
	return loadConfigFromFlags(), nil
}

// loadConfigFromFlags loads configuration from Cobra flags.
func loadConfigFromFlags() *llm.LLMConfig {
	return &llm.LLMConfig{
		Model:            genaiArgs.model,
		URL:              genaiArgs.endpoint,
		UserPrompt:       genaiArgs.prompt,
		Assistant:        genaiArgs.assistant,
		UserSystemPrompt: genaiArgs.userSystemPrompt,
	}
}

// mergeFlagsWithConfig merges the flag values with the config if the flag values are not empty.
func mergeFlagsWithConfig(config *llm.LLMConfig) {
	if genaiArgs.model != "" {
		config.Model = genaiArgs.model
	}
	if genaiArgs.endpoint != "" {
		config.URL = genaiArgs.endpoint
	}
	if genaiArgs.prompt != "" {
		config.UserPrompt = genaiArgs.prompt
	}
	if genaiArgs.assistant != "" {
		config.Assistant = genaiArgs.assistant
	}
	if genaiArgs.userSystemPrompt != "" {
		config.UserSystemPrompt = genaiArgs.userSystemPrompt
	}
}
