apiVersion: genval/genai/v1beta1
metadata:
  name: test-config
llmSpec:
  model: GPT4
  assistant: dockerfile
  apiKey: OPENAI_KEY
  userPrompt: ./templates/inputs/genai/prompt.txt
  maxTokens: 2048
  presencePenalty: 0.0
  frequencyPenalty: 0.0
  topP: 0.8
  temperature: 0.7
