apiVersion: genval/genai/v1beta1
metadata:
  name: cue-config
requirementSpec:
  common:
    userPrompt: ./templates/inputs/genai/user-prompts/cue-prompt.md
    assistant: cue
  llmSpec:
    openAIConfig:
      - model: GPT4
        # assistant: cue
        useTheModel: true
        apiKey: OPENAI_KEY
        temperature: 0.7
        topP: 0.3
        streaming: true
        maxTokens: 2048
