apiVersion: genval/genai/v1beta1
metadata:
  name: dockerfile-config
requirementSpec:
  common:
    userPrompt: ./templates/inputs/genai/user-prompts/dockerfile-prompt.md
    assistant: dockerfile
  llmSpec:
    openAIConfig:
      - model: GPT4
        # assistant defined in this block takes precedence
        assistant: dockerfile
        useTheModel: true
        apiKey: OPENAI_KEY
        temperature: 0.7
        topP: 0.3
        streaming: true
        maxTokens: 2048
