apiVersion: genval/genai/v1beta1
metadata:
  name: test-config
requirementSpec:
  common:
    userPrompt: ./templates/inputs/genai/prompt.txt
    assistant: dockerfile
    model: GPT4
  llmSpec:
    openAIConfig:
      apiKey: OPENAI_KEY
      temperature: 0.7
      topP: 0.3
      streaming: True
      maxTokens: 2048
