apiVersion: genval/genai/v1beta1
metadata:
  name: regex-config
requirementSpec:
  common:
    userPrompt: ./templates/inputs/genai/user-prompts/regex-prompt.md
    output: ./output/regex-llmResponse.md
    # assistant: cel
  llmSpec:
    openAIConfig:
      - model: GPT4
        assistant: regex
        useTheModel: true
        apiKey: OPENAI_KEY
        temperature: 0.7
        topP: 0.3
        streaming: true
        maxTokens: 2048
