apiVersion: genval/genai/v1beta1
metadata:
  name: test-config
requirementSpec:
  common:
    userPrompt: ./templates/inputs/genai/prompt.txt
    userSystemPrompt:
  llmSpec:
    openAIConfig:
      - model: GPT4
        assistant: dockerfile
        useTheModel: true
        apiKey: OPENAI_KEY
        temperature: 0.7
        topP: 0.3
        streaming: true
        maxTokens: 2048
