name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - "main"
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "pre-main" ] && [ ${{ github.base_ref }} == "main" ]; then
            echo "ERROR: Merge requests to main branch are only allowed from 'pre-main' branch."
            exit 1
          fi
